#!/bin/bash

PACKAGE_VERSION=$(cat package.json | jq -r '.version');

echo "PACKAGE_VERSION:$PACKAGE_VERSION";
echo "CURRENT_BRANCH:$CURRENT_BRANCH";

echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV;
echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV;