name: CI Docker Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: docker build --cache-from tahinguyen/core-fe:latest -t tahinguyen/core-fe:latest -t tahinguyen/core-fe:$COMMIT_SHA .
      - name: Push to Dockerhub
        run: docker push --all-tags tahinguyen/core-fe
