name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Docker Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull abc/xxx:latest

      - name: Delete Old docker container
        run: docker rm -f xxx || true

      - name: Run Docker Container
        env:
          PORT: ${{secrets.PORT}}
        run: |
          docker run -d -p $PORT:$PORT --restart unless-stopped --env-file ~/.env --name xxx abc/xxx:latest
