name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Docker Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: docker pull tahinguyen/core-fe:latest

      - name: Delete Old docker container
        run: docker rm -f core-fe-ctn || true

      - name: Run Docker Container
        env:
          PORT: ${{secrets.PORT}}
        run: |
          docker run -d -p $PORT:$PORT --restart unless-stopped --env-file ~/core-fcm-team/.env --name core-fe-ctn tahinguyen/core-fe:latest
